apps/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path("register/",views.RegisterUserView.as_view(),name="register"),
    path("verify/",views.VerifyRegisterCodeView.as_view(),name="verify"),
    path("login/",views.LoginUserView.as_view(),name="login"),
    path("logout/",views.LogoutUserView.as_view(),name="logout"),
    path("change_password/<int:type>/",views.ChangePasswordView.as_view(),name="change_password"),
    path("SendCode/",views.SendCodeView.as_view(),name="SendCode"),
    path("AuthCode/",views.AuthCodeView.as_view(),name="AuthCode"),
    
    path("userpanel/",views.UserPanelView.as_view(),name="userpanel"),
    path("show_last_orders/",views.show_last_orders,name="show_last_orders"),
    path("update_profile/",views.UpdateProfileView.as_view(),name="update_profile"),
    path("show_user_payments/",views.show_user_payments,name="show_user_payments"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("ckeditor",include("ckeditor_uploader.urls")),
    path("orders/",include("apps.orders.urls", namespace="orders")),
    path("discount/",include("apps.discount.urls", namespace="discount")),
    path("payments/",include("apps.payments.urls", namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls", namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls", namespace="csf")),              # comment_scoring_favorites
    path("search/",include("apps.search.urls", namespace="search")),
    path("test_api/",include("apps.test_api.urls", namespace="test_api")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = "apps.main.views.ErrorHandler404"                          # handler404 hatman bayad esmesh hamin bashe. age user to url addresse eshtebah bezane in page ro neshun mide. settings.py => DEBUG=False, ALLOWED_HOSTS = ['*']

templates/accounts_app/AuthCode.html
{% extends 'main_template.html' %}

{% block title %} Account  {% endblock title %}

{% block content %}

<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">خانه</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="">حساب کاربری</a>
                            /
                        </li>
                        <li class="active" aria-current="page"> ایجاد حساب کاربری</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title d-flex justify-content-center">
                <h1>Authentication</h1></div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 d-flex mt-4 mt-md-0">
                    <div class="card flex-grow-1 mb-0">
                        <div class="card-body">
                            <h3 class="card-title">Authentication</h3>
                            <form action="" method="post">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary mt-4">Authenticate</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/accounts_app/SendCode.html
{% extends 'main_template.html' %}

{% block title %} Account  {% endblock title %}

{% block content %}

<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="">Account</a>
                            /
                        </li>
                        <li class="active" aria-current="page"> Login</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title d-flex justify-content-center">
                <h1>Send Code</h1></div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 d-flex mt-4 mt-md-0">
                    <div class="card flex-grow-1 mb-0">
                        <div class="card-body">
                            <h3 class="card-title">Send Code</h3>
                            <form action="" method="post">                          <!-- chon action="" hast pas bar migardune be adressi ke omade -->
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary mt-4">Send SMS</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/accounts_app/change_password.html
{% extends template %}                      <!-- template to view tarif shode. change_password to har 2ta template estefade shode -->

{% block title %} Account  {% endblock title %}

{% block content %}

<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home &nbsp;</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#">Account &nbsp;</a>
                            / &nbsp;  
                        </li>
                        <li class="active" aria-current="page"> Change Password</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 d-flex mt-4 mt-md-0">
                    <div class="card flex-grow-1 mb-0">
                        <div class="card-body">
                            <h3 class="card-title">Change Password</h3>
                            
                            <form action="" method="post">                              <!-- chon action="" khaliye pas bar migardne be addressi ke omade -->
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary mt-4">Change</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/accounts_app/login.html
{% extends 'main_template.html' %}

{% block title %} Login  {% endblock title %}

{% block content %}
    	<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">Home</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">Account</a>
									/
								</li>
								<li class="active" aria-current="page">Login</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>Login to the account</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">
									<h3 class="card-title">Login</h3>
                                        <form action="" method="post">
                                            {% csrf_token %}
                                            {{form.as_p}}
											<div>
												<a href=" {% url 'accounts:SendCode' %}">
													Forget Password
												</a>
											</div>
                                            <button type="submit" class="btn btn-primary mt-4">Login</button>
                                        </form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock content %}

templates/accounts_app/register.html
{% extends 'main_template.html' %}

{% block title %} Account  {% endblock title %}

{% block content %}

<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="">Accoun</a>
                            /
                        </li>
                        <li class="active" aria-current="page">Create New Account</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title d-flex justify-content-center">
                <h1>Create New Account</h1></div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 d-flex mt-4 mt-md-0">
                    <div class="card flex-grow-1 mb-0">
                        <div class="card-body">
                            <h3 class="card-title">Register Form</h3>
                            <form action="" method="post">
                                {% csrf_token %}
                                {{form.as_p}}
                                <button type="submit" class="btn btn-primary mt-4">Register</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

templates/accounts_app/show_user_payments.html
{% extends 'user_panel_template.html' %}
{% load render_partial %}
{% load humanize %}

{% block title %} User Payments  {% endblock title %}

{% block content %}
    <div class="dashboard__orders card">
        <div class="card-header">
            <h5>Payment List</h5>
        </div>
        <div class="card-divider"></div>
        <div class="card-table">
            <div class="table-responsive-sm">
                <table>
                    <thead>
                        <tr>
                            <th>Order Id</th>
                            <th>Payment Date</th>
                            <th>state</th>
                            <th>Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for payment in payments %}               <!--  objectha(recordha) ke dar model Payment hastan ro miyare -->
                            <tr>
                                <td>{{payment.id}}</td>
                                <td>{{payment.register_date}}</td>
                                <td>
                                    {% if payment.is_finally %}
                                        <span class="text-success">Paid</span>
                                    {% else %}
                                        <span class="text-danger">UnPaid</span>
                                    {% endif %}
                                </td>
                                <td>{{payment.amount|intcomma}} $</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts_app/update_profile.html
{% extends 'user_panel_template.html' %}
{% load render_partial %}

{% block title %} Update Profile  {% endblock title %}

{% block content %}

<div class="block">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                <div class="card">
                    <div class="card-header">
                        <h5>Edit Profile</h5>
                    </div>
                    <div class="card-divider"></div>
                    
                    <div class="card-body">
                        <form action="" method="POST" enctype="multipart/form-data">     <!-- age action="" khali bashe bar migardune be hamun address ke omade. enctype baraye ersal file(image) bud -->
                            {% csrf_token %}    
                            {{form.as_p}}                           <!---->
                            <img src="{{media_url}}{{image_url}}" style="width: 100px; height: 100px;" alt="image">     <!---->
                            <div class="form-group">                                            
                                <button type="submit" class="btn btn-primary mt-4">Save</button>                        <!---->
                                <a href="{% url 'accounts:userpanel' %}" class="btn btn-info mt-4">Cancel</a>           <!---->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts_app/userpanel.html
{% extends 'user_panel_template.html' %}     <!-- main template fargh mikone, main temple = user_panel_template.html -->
{% load render_partial %}

{% block title %} User Panel  {% endblock title %}

{% block content %}

    <div class="dashboard">
        {% include 'accounts_app/partials/user_info.html' %}
        {% render_partial 'accounts:show_last_orders' %}
    </div>

{% endblock content %}

templates/accounts_app/verify_register.html
{% extends 'main_template.html' %}

{% block title %} Verification  {% endblock title %}

{% block content %}
    <form action="" method="post">
        		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">Home</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">Account</a>
									/
								</li>
								<li class="active" aria-current="page">Register</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>Activation Code</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">
                                
									<form>
                                        <div class="form-group">
                                            {% csrf_token %}
                                            <label>Activation Code</label>
                                            {{form.as_p}}
                                        </div>
                                        <button type="submit" class="btn btn-primary mt-4">Send</button>
                                    </form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
    </form>
{% endblock content %}