apps/products/urls.py
from django.urls import path
from . import views

app_name="products"
urlpatterns = [
    path("cheapest_products/",views.get_cheapest_products,name="cheapest_products"),
    path("last_products/<str:widget>/",views.get_last_products,name="last_products"),           # because we use /str:widget/, in html file we should give it paramtere
    path("most_purchased_products/",views.get_most_purchased_products,name="most_purchased_products"),
    path("popular_productGroups/",views.get_popular_productGroups,name="popular_productGroups"),
    path("ProductDetail/<slug:slug>/",views.ProductDetailView.as_view(),name="ProductDetail"),                # models.py => Product => def get_absolute_url(self)
    path("related_products/<slug:slug>/",views.get_related_products,name="related_products"),                 # product_detail.html => 
    path("product_groups/",views.ProductGroupsView.as_view(),name="product_groups"),
    path("product_groups_partial/",views.get_product_groups,name="product_groups_partial"),
    path("products_of_group/<slug:slug>/",views.ProductsOfGroup.as_view(),name="products_of_group"),
    path("brands_partial/<slug:slug>/",views.get_brands,name="brands_partial"),                         # when we use /<slug:slug>/, in html file we should give it parmater
    path("features_for_filter/<slug:slug>/",views.get_features_for_filter,name="features_for_filter"),
    path("ajax_admin/",views.get_filter_value_for_feature,name="filter_value_for_feature"),
    path("compare_list/",views.showCompareListViw.as_view(),name="compare_list"),
    path("compare_table/",views.compare_table,name="compare_table"),
    path("add_to_compare_list/",views.add_to_compare_list,name="add_to_compare_list"),
    path("status_of_compare_list/",views.status_of_compare_list,name="status_of_compare_list"),
    path("delete_from_compare_list/",views.delete_from_compare_list,name="delete_from_compare_list"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("ckeditor",include("ckeditor_uploader.urls")),
    path("orders/",include("apps.orders.urls", namespace="orders")),
    path("discount/",include("apps.discount.urls", namespace="discount")),
    path("payments/",include("apps.payments.urls", namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls", namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls", namespace="csf")),              # comment_scoring_favorites
    path("search/",include("apps.search.urls", namespace="search")),
    path("test_api/",include("apps.test_api.urls", namespace="test_api")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = "apps.main.views.ErrorHandler404"                          # handler404 hatman bayad esmesh hamin bashe. age user to url addresse eshtebah bezane in page ro neshun mide. settings.py => DEBUG=False, ALLOWED_HOSTS = ['*']

templates/products_app/partials/brands.html
{% load humanize %}

<div class="widget-filters__item">
    <div class="filter filter--opened" data-collapse-item>                                  <!-- item -->
        <button type="button" class="filter__title" data-collapse-trigger>Brand              <!-- trigger -->
            <svg class="filter__arrow" width="12px" height="7px">
                <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
            </svg>
        </button>
        <div class="filter__body" data-collapse-content>                                     <!-- content -->
            <div class="filter__container">
                {% for brand in brands %}
                    <input id="item1_{{brand.id}}" type="checkbox" name="brand" value="{{brand.id}}"  >
                    <span class="filter-list__title">{{brand.brand_title}}</span>
                    {% comment %} <span class="filter-list__counter">{{brand.products_brand.all|length}}</span> {% endcomment %}    <!-- it shows all the products with this brand, It doesn't consider current_group -->
                    <span class="filter-list__counter">{{brand.count}}</span>   <!-- It considers products that have this brand and this current_group -->
                    <br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/products_app/partials/cheapest_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include "partials/productGroups.html" with title="Cheapest Products" %}           <!-- mishe include nakoni va haminja benevisi -->
        {% include "partials/Products.html" with type=1 %}                                   <!-- include ba with mitune value ba khodesh bebare -->
    </div>
</div>
    

templates/products_app/partials/compare_table.html
{% if products %}
    <div class="container">
        <h2 style="text-align: center; color: reen;">Compare Products</h2>
        <table class="table table-bordered">
            <!-- Th -->
            <tr style="background: #f1f1f1; text-align:center;">
                <th>Product Features</th>
                {% for product in products %}
                    <th>
                        <i class="fa fa-times product-remove" onclick="deleteFromCompareList({{product.id}})"></i>       <!---->
                        {{product.product_name}}
                    </th>
                {% endfor %}
            </tr>
            <!-- /Th-->

            <!-- Td -->
            {% for feature in features %}
                <tr>                                                        
                    <td style="font-size:1.2rem; font-weight:900; width: 25%;">
                        {{feature}}                                                 <!-- def __str__(self) miyad self.feature_name ro chap mikone-->
                    </td>

                    {% for product in products %}
                        <td style="text-align:center;">
                            {% for ProductFeature in product.product_features.all %}      <!-- ManyToMany. Product => ProductFeature(table) => product_features. ProductFeature haro miyare -->
                                {% if ProductFeature.feature == feature %}
                                    <span style="margin:5px;"> {{ProductFeature.filter_value.value_title}} </span>            <!---->
                                {% endif %}
                            {% endfor %}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            <!-- /Td -->
        </table>
    </div>
{% else %}
    <div class="container">
        <h2 style="text-align:center; color:green; padding: 100px;"> There is no product to compare</h2>
    </div>
{% endif %}

templates/products_app/partials/features_filter.html
{% load humanize %}

{% for key,value in feature_dict.items %}
    {% if value %}
        <div class="widget-filters__item">
            <div class="filter filter--opened" data-collapse-item>                                  <!-- item -->
                <button type="button" class="filter__title" data-collapse-trigger>{{key}}              <!-- trigger --> <!---->
                    <svg class="filter__arrow" width="12px" height="7px">
                        <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
                    </svg>
                </button>
                <div class="filter__body" data-collapse-content>                                     <!-- content -->
                    <div class="filter__container">
                        {% for item in value %}                                                      
                            <input id="item2_{{item.id}}" type="checkbox" name="featureValue" value="{{item.id}}" >           <!-- name="featureValue". ref=> views => features_filter -->
                            <span class="filter-filter-list__title">{{item.value_title}}</span>          <!---->           
                            <br>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

templates/products_app/partials/last_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include "partials/productGroups.html" with title="Last Products" %}       
        {% include "partials/Products.html" with type=2 %}
    </div>
</div>

templates/products_app/partials/most_purchased_products.html
{% include "partials/Products.html" with type=5 %}


    

templates/products_app/partials/popular_productGroups.html
<div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">Popular Groups</h3>
            <div class="block-header__divider"></div>
        </div>
            <div class="block-categories__list">
                {% for group in product_groups %}
                <div class="block-categories__item category-card category-card--layout--compact">
                    <div class="category-card__body">
                        <div class="category-card__image">
                            <a href=" {% url 'products:products_of_group' slug=group.slug %}">            <!---->
                                <img src="{{media_url}}{{group.image_name}}" alt="">
                            </a>
                        </div>
                        <div class="category-card__content">
                            <div class="category-card__name">
                                <a href="{% url 'products:products_of_group' slug=group.slug %}"> {{group.group_title}}</a>
                            </div>
                            <div class="category-card__products">{{group.count}}</div>                      <!-- {{group.products_of_group.all|length}} ham mishe-->
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="block-categories__item category-card category-card--layout--compact">
                    <div class="category-card__body">
                        <a href=" {% url 'products:product_groups' %}" style="font-size: 2rem; margin-left: 70px; margin-top: -4px;">All Groups</a>         <!---->
                    </div>
                </div>
            </div>
    </div>
</div>

templates/products_app/partials/price_filter.html
{% load humanize %}

<div class="widget-filters__item">
    <div class="filter filter--opened" data-collapse-item>                                  <!-- item -->
        <button type="button" class="filter__title" data-collapse-trigger>Price              <!-- trigger -->
            <svg class="filter__arrow" width="12px" height="7px">
                <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
            </svg>
        </button>
        <div class="filter__body" data-collapse-content>                                     <!-- content -->
            <div class="filter__container">
                <span><strong id="sel_price">{{res_aggre.min|intcomma }}</strong></span><br>
                {% comment %} {{filter.form}}  {% endcomment %}                              <!---->
                <!-- this.value means the value of this input -->
                <input id="inputVal" type="range" name="price" min="{{res_aggre.min}}" max="{{res_aggre.max}}"
                 value="{{price}}" oninput="showValue(this.value)" onchange="showValue(this.value)" 
                 style="width:100%;"> 
                <br>
                <span>{{res_aggre.min|intcomma}}</span>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span style="margin-left:100px;">{{res_aggre.max|intcomma}}</span>
            </div>
        </div>
    </div>
</div>

templates/products_app/partials/product_groups.html
<ul class="filter-categories__list">
    {% for group in product_groups %}
        <li class="filter-categories__item filter-categories__item--current">
            <a href="{% url 'products:products_of_group' slug=group.slug %}">{{ group.group_title }}</a>
            <div class="filter-categories__counter">{{group.products_of_group.all|length}}</div>
        </li>
    {% endfor %}
</ul> 

templates/products_app/partials/related_products.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include "partials/Products.html" with type=3 %}
    </div>
</div>

templates/products_app/partials/widget_last_products.html
<div class="block-sidebar__item d-none d-lg-block">
    <div class="widget-products widget">
        {% include "partials/Products.html" with type=6 %}
    </div>
</div>