apps/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path("register/",views.RegisterUserView.as_view(),name="register"),
    path("verify/",views.VerifyRegisterCodeView.as_view(),name="verify"),
    path("login/",views.LoginUserView.as_view(),name="login"),
    path("logout/",views.LogoutUserView.as_view(),name="logout"),
    path("change_password/<int:type>/",views.ChangePasswordView.as_view(),name="change_password"),
    path("SendCode/",views.SendCodeView.as_view(),name="SendCode"),
    path("AuthCode/",views.AuthCodeView.as_view(),name="AuthCode"),
    
    path("userpanel/",views.UserPanelView.as_view(),name="userpanel"),
    path("show_last_orders/",views.show_last_orders,name="show_last_orders"),
    path("update_profile/",views.UpdateProfileView.as_view(),name="update_profile"),
    path("show_user_payments/",views.show_user_payments,name="show_user_payments"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("ckeditor",include("ckeditor_uploader.urls")),
    path("orders/",include("apps.orders.urls", namespace="orders")),
    path("discount/",include("apps.discount.urls", namespace="discount")),
    path("payments/",include("apps.payments.urls", namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls", namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls", namespace="csf")),              # comment_scoring_favorites
    path("search/",include("apps.search.urls", namespace="search")),
    path("test_api/",include("apps.test_api.urls", namespace="test_api")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = "apps.main.views.ErrorHandler404"                          # handler404 hatman bayad esmesh hamin bashe. age user to url addresse eshtebah bezane in page ro neshun mide. settings.py => DEBUG=False, ALLOWED_HOSTS = ['*']

templates/main_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css -->
	<link rel="stylesheet" href=" {% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href=" {% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %}">
	<link rel="stylesheet" href=" {% static 'css/custom.css' %}">
	<link rel="stylesheet" href=" {% static 'css/style.css' %}">
	
	<!-- js -->
	{% comment %} <script src=" {% static 'vendor/jquery-3.3.1/jquery.min.js' %}"></script> {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src=" {% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %}"></script>
	<script src=" {% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %}"></script>
	<script src=" {% static 'js/main.js' %}"></script>
	<script src=" {% static 'js/myScript.js' %}"></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href=" {% static 'vendor/fontawesome-5.6.3/css/all.min.css' %}">

    <title>
        {% block title %}{% endblock title %}
    </title>
</head>
<body>
    {% include "partials/header.html" %}
    {% include "partials/messages.html" %}

    {% block content %}
    {% endblock content %}

    {% include "partials/footer.html" %}
</body>
</html>

templates/user_panel_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- css -->
	<link rel="stylesheet" href=" {% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href=" {% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %}">
	<link rel="stylesheet" href=" {% static 'css/custom.css' %}">
	<link rel="stylesheet" href=" {% static 'css/style.css' %}">
	<!-- js -->
	<script src=" {% static 'vendor/jquery-3.3.1/jquery.min.js' %}"></script>
	<script src=" {% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %}"></script>
	<script src=" {% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %}"></script>
	<script src=" {% static 'js/main.js' %}"></script>
	<script src=" {% static 'js/myScript.js' %}"></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href=" {% static 'vendor/fontawesome-5.6.3/css/all.min.css' %}">

    <title>
        {% block title %}{% endblock title %}
    </title>
</head>
<body>
    {% include "partials/header.html" %}
    {% include "partials/messages.html" %}

    <div class="site__body">
        <div class="page-header">
            <div class="page-header__container container">
                <div class="page-header__title">
                    <h1>Account</h1></div>
            </div>
        </div>
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-lg-3 d-flex">
                        <div class="account-nav flex-grow-1">
                            <h4 class="account-nav__title">Toolbar</h4>
                            <ul>
                                <li class="account-nav__item account-nav__item--active"><a href="{% url 'accounts:userpanel' %}">Dashboard</a></li>
                                <li class="account-nav__item"><a href="{% url 'accounts:update_profile' %}">Edit Profile</a></li>
                                <li class="account-nav__item"><a href="{% url 'accounts:show_user_payments' %}">Purchase History</a></li>
                                <li class="account-nav__item"><a href="{% url 'accounts:change_password' type=1 %}">Change Password</a></li>
                                <li class="account-nav__item"><a href=" {% url 'accounts:logout' %} ">Exit</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                        {% block content %}{% endblock content %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "partials/footer.html" %}

</body>
</html>