apps/orders/urls.py
from django.urls import path
from . import views

app_name="orders"
urlpatterns = [
    path("shop_cart/",views.ShopCartView.as_view(),name="shop_cart"),
    path("add_to_shop_cart/",views.add_to_shop_cart,name="add_to_shop_cart"),
    path("delete_from_shop_cart/",views.delete_from_shop_cart,name="delete_from_shop_cart"),
    path("show_shop_cart/",views.show_shop_cart,name="show_shop_cart"),
    path("update_shop_cart/",views.update_shop_cart,name="update_shop_cart"),
    path("status_of_shop_cart/",views.status_of_shop_cart,name="status_of_shop_cart"),
    path("create_order/",views.CreateOrderView.as_view(),name="create_order"),
    path("checkout_order/<int:order_id>/<str:coupon_code>/",views.CheckOutOrderView.as_view(),name="checkout_order"),
    path("apply_coupon/<int:order_id>/",views.ApplyCoupon.as_view(),name="apply_coupon"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("ckeditor",include("ckeditor_uploader.urls")),
    path("orders/",include("apps.orders.urls", namespace="orders")),
    path("discount/",include("apps.discount.urls", namespace="discount")),
    path("payments/",include("apps.payments.urls", namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls", namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls", namespace="csf")),              # comment_scoring_favorites
    path("search/",include("apps.search.urls", namespace="search")),
    path("test_api/",include("apps.test_api.urls", namespace="test_api")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

handler404 = "apps.main.views.ErrorHandler404"                          # handler404 hatman bayad esmesh hamin bashe. age user to url addresse eshtebah bezane in page ro neshun mide. settings.py => DEBUG=False, ALLOWED_HOSTS = ['*']

templates/orders_app/checkout.html
{% extends 'main_template.html' %}
{% load render_partial %}
{% load humanize %}

{% block title %}
    Checkout
{% endblock  %}

{% block content %}
<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a>
                            /
                        </li>
                        
                        <li class="breadcrumb-item active" aria-current="page">Payment</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title">
                <h1>پرداخت</h1></div>
        </div>
    </div>
    <div class="checkout block">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-3">
                    {% if not user.is_authenticated %}
                        <div class="alert alert-lg alert-primary">Login to your<a href="/accounts/login">Account</a></div>
                    {% endif %}
                </div>
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="card mb-lg-0">
                        <form action="{% url 'orders:checkout_order' order_id=order.id coupon_code=None %}" method="post">            <!---->
                            {% csrf_token %}                                                      
                            <div class="card-body">                                             
                                <h3 class="card-title">Payment Details</h3>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="checkout-first-name">Name</label>
                                        <!-- <input type="text" class="form-control" id="checkout-first-name" placeholder="نام" name="name" value="{{user.name}}"> -->       <!-- age mikhastim module form ro nasazim mishod value ro biyarim -->
                                        {{form.name}}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="checkout-last-name">Family</label>
                                        {% comment %} <input type="text" class="form-control" id="checkout-last-name" placeholder="نام خانوادگی"> {% endcomment %}
                                        {{form.family}}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="checkout-street-address">Address</label>
                                    {% comment %} <input type="text" class="form-control" id="checkout-street-address" placeholder="آدرس "> {% endcomment %}
                                    {{form.address}}
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="checkout-email">Email</label>
                                        {% comment %} <input type="email" class="form-control" id="checkout-email" placeholder="آدرس ایمیل"> {% endcomment %}
                                        {{form.email}}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="checkout-phone">Phone Number</label>
                                        {% comment %} <input type="text" class="form-control" id="checkout-phone" placeholder="تلفن"> {% endcomment %}
                                        {{form.phone_number}}
                                    </div>
                                </div>
                                <div class="card-divider"></div>
                                
                                <div class="card-body">
                                    <h3 class="card-title">Delivery Details</h3>
                                    <div class="form-group">
                                        <label for="checkout-comment">Description 
                                            <span class="text-muted">(Optional)</span>
                                        </label>
                                        {% comment %} <textarea id="checkout-comment" class="form-control" rows="4"></textarea> {% endcomment %}
                                        {{form.description}}
                                    </div>
                                    <div class="form-group">
                                        {{form.payment_type}}                            <!---->
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary btn-xl btn-block">Place Order</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-12 col-lg-6 col-xl-5 mt-4 mt-lg-0">
                    <div class="card mb-0">
                        <div class="card-body">
                            <h3 class="card-title"> Order Details</h3>
                            <table class="checkout__totals">
                                <thead class="checkout__totals-header">
                                    <tr>
                                        <th>Product</th>
                                        <th style="width: 20%;">Quantity</th>
                                        <th>Total Price</th>
                                    </tr>
                                </thead>
                                <tbody class="checkout__totals-products">
                                    <!-- az shop_cart har item ro bar midearim neshun midim -->
                                    {% for item in shop_cart %}                                
                                    <tr>
                                        <td>{{item.product}}</td>
                                        <td>{{item.qty}}</td>
                                        <td>{{item.total_price|intcomma}} $</td>
                                    </tr>
                                    {% endfor %}

                                    <!-- hamun kare balayi ro mikone, faghat az order, order_Detail haro miyare -->
                                    {% comment %} {% for orderDetail in order.order_Details.all %}
                                        <tr>
                                            <td>{{orderDetail.product}}</td>
                                            <td>{{orderDetail.qty}}</td>
                                            <td>{{orderDetail.price|intcomma}}</td>
                                        </tr>
                                    {% endfor %} {% endcomment %}
                                </tbody>
                                <tbody class="checkout__totals-subtotals">
                                    <tr>    
                                        <th colspan="2">Price</th>
                                        <td>{{total_price|intcomma}} $</td>
                                    </tr>
                                    <tr>
                                        <th colspan="2">Delivery</th>                         <!-- colspan="2" -->                            
                                        <td>{{delivery|intcomma}} $</td>  
                                    </tr>
                                    <tr>    
                                        <th colspan="2">Tax</th>
                                        <td>{{tax|intcomma}} $</td>
                                    </tr>
                                </tbody>
                                <tfoot class="checkout__totals-footer">
                                    <tr style="color:green; font-weight:900;">
                                        <th colspan="2" style="width:75%;">Total Price</th>
                                        <td>{{order_final_price|intcomma}} $</td>
                                    </tr>
                                </tfoot>
                            </table>
                            <form action="{% url 'orders:apply_coupon' order_id=order.id %}" method="post" style="display:flex; justify-content: center;">        <!-- mishod az tarighe ajax va jquery ham in kar ro anjam dad -->
                                {% csrf_token %}                    
                                {{form_coupon}}                                                       <!---->
                                <button type="submit" class="btn btn-primary">apply</button>
                            </form>
                            {% if coupon_code != "None" %}              <!---->
                                <div style="margin: 10px 0 10px 0">Coupon: <span style="color:red; font-weight:600;">{{coupon_code}}</span> Added</div>
                            {% endif %}

                            <div class="checkout__agree form-group">
                                <div class="form-check">
                                    <span class="form-check-input input-check">
                                        <span class="input-check__body">
                                            <input class="input-check__input" type="checkbox" id="checkout-terms">
                                            <span class="input-check__box"></span>
                                        </span>
                                    </span>
                                    
                                    <label class="form-check-label" for="checkout-terms" style="margin-left:25px;">I read the <a target="_blank" href="terms-and-conditions.html">rules</a> and accept them</label>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

templates/orders_app/shop_cart.html
{% extends 'main_template.html' %}
{% load render_partial %}

{% block title %}
    Shop Cart
{% endblock  %}

{% block content %}
    <div id="shop_cart_list">
        {% render_partial "orders:show_shop_cart" %}
    </div>
{% endblock  %}